### ISSUE TITLE
无法解析番剧

### ISSUE THREAD

**Issue by africa1207** [Majjcom/BiliDownloader#12]
1.2.0，已登录大会员账号，无法解析番剧
![image](https://github.com/Majjcom/BiliDownloader/assets/21698755/6954972f-d7ef-4174-823c-b0f89fbd7535)
![image](https://github.com/Majjcom/BiliDownloader/assets/21698755/336d5aef-863f-4322-a1f3-481d62036c8e)

**Comment by Majjcom** [comment]
对于番剧剧集，不要用bv,av号解析，请使用ep,md号解析

**Comment by Majjcom** [comment]
![屏幕截图 2024-04-30 101256](https://github.com/Majjcom/BiliDownloader/assets/55314301/bbb2c2ca-a2cb-41b7-b52c-47708c58ac72)
![屏幕截图 2024-04-30 101337](https://github.com/Majjcom/BiliDownloader/assets/55314301/8b028858-a9c9-4be0-b4ec-98ec3796233f)
![屏幕截图 2024-04-30 101353](https://github.com/Majjcom/BiliDownloader/assets/55314301/9a5eae58-f153-420b-86cf-c16a553529da)

**Comment by Majjcom** [comment]
md号可以在播放页点击番剧封面进入番剧详情介绍，在网页链接中获取

**Comment by Majjcom** [comment]
还有问题的话我再跟进

**Comment by africa1207** [comment]
可行，谢谢
