### ISSUE TITLE
视频链接获取错误

### ISSUE THREAD

**Issue by FlipWind** [Majjcom/BiliDownloader#13]
出错番剧：https://www.bilibili.com/bangumi/play/ep35595/
报错：
![image](https://github.com/Majjcom/BiliDownloader/assets/89458091/52442a06-c613-450f-8a74-de809f713663)

日志：没找到（）
版本：1.2.1
附注：有大会员，确认当前网络环境时可以下载其他番剧

**Comment by Majjcom** [comment]
收到，这段时间研究一下是什么问题

**Comment by Majjcom** [comment]
好像是B站的问题

第一集的下载有问题，其他正常

修复方案已经准备好了

**Comment by Majjcom** [comment]
在1.2.2版本中已修复。

更新已推送
