### ISSUE TITLE
卡在下载界面

### ISSUE THREAD

**Issue by th10010** [Majjcom/BiliDownloader#14]
在下载b站纪录片的过程中，会出现卡住没有进度的情况，可参考图片。
视频链接：
https://www.bilibili.com/bangumi/play/ep828220?spm_id_from=333.337.0.0&from_spmid=666.25.episode.0
附图：
![122](https://github.com/Majjcom/BiliDownloader/assets/55772277/8de5a8c2-3c2d-4bae-a89b-f8496b6cb0eb)

**Comment by Majjcom** [comment]
我这边下载是没有问题的，可能是网络的原因。

如图：
![屏幕截图 2024-07-08 231425](https://github.com/Majjcom/BiliDownloader/assets/55314301/03246368-ba6f-4a1c-8339-5363d11ceebf)

有问题我在跟进
