### ISSUE TITLE
关于win7显示缺失库

### ISSUE THREAD

**Issue by Lazywenxin** [Majjcom/BiliDownloader#15]
话说这个是不兼容win7吗，1.3.0和1.2.2都试过了，朋友的电脑win7我win10，我这边跑得起来他不太行

**Comment by Majjcom** [comment]
不兼容Win7，如果需要兼容Win7的版本，可以到下面的地址下载上一个大版本的最终版：
[https://majjcom.lanzouy.com/b01utd3da](https://majjcom.lanzouy.com/b01utd3da) 密码:6ww7

版本号应该是0.13.1final

**Comment by Lazywenxin** [comment]
非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月8日(星期一) 晚上11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Majjcom/BiliDownloader] 关于win7显示缺失库 (Issue #15)














 
不兼容Win7，如果需要兼容Win7的版本，可以到下面的地址下载上一个大版本的最终版：
 https://majjcom.lanzouy.com/b01utd3da 密码:6ww7
 
版本号应该是0.13.1final

**Comment by Lazywenxin** [comment]
能用已经很可以了，其他的没找到能下番剧的，非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月8日(星期一) 晚上11:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Majjcom/BiliDownloader] 关于win7显示缺失库 (Issue #15)














 
那个版本也只能是凑合这用了，有很多BUG没修
