### ISSUE TITLE
程序安装卡死无法完成安装

### ISSUE THREAD

**Issue by fly0982** [Majjcom/BiliDownloader#17]
**描述BUG**
安装程序卡死在 状态：准备要删除的文件界面。

**复现步骤**
解压缩直接点击安装即出现问题，反复尝试多次依旧如此。

**屏幕截图**
![捕获](https://github.com/user-attachments/assets/91c2e70a-3734-4c31-84df-19a7c7aee511)

**你使用的系统是：**
Windows 10

**其他说明**
如果还有其他情况，在这里说明。

**Comment by Majjcom** [comment]
我们需要更详细的系统信息来定位问题。

**Comment by Majjcom** [comment]
因为没有回应，故关闭此issue
