### ISSUE TITLE
直接从任务栏快捷方式启动时程序权限出现故障

### ISSUE THREAD

**Issue by 1298882690** [Majjcom/BiliDownloader#18]
**描述BUG**
桌面快捷方式及exe启动正常，将启动的程序固定到任务栏，关闭程序，再次通过任务栏启动时出现异常，表现为无法读取之前设置的windows DPI兼容性、程序自身的保存设置、下载视频停留在使用ffmpeg合并中无法调用ffmpeg

**复现步骤**
请给出能够复现BUG的步骤
1. 将启动的程序固定到任务栏
2. 关闭程序
3. 再次通过任务栏图标启动

**预期的效果**
请描述一下你对该程序预期的效果

**屏幕截图**
1、桌面快捷方式及exe启动
![image](https://github.com/user-attachments/assets/8864cd29-ff8f-450d-b6d1-0817e91190bc)
2、任务栏快捷方式启动
![image](https://github.com/user-attachments/assets/5b457215-4236-4b40-abb3-68d28c99b272)

**你使用的系统是：**
windwos10

**其他说明**
程序安装位置：C:\Program Files\Majjcom\BiliDownloader\BiliDownloader
正在使用的用户拥有管理员权限

**Comment by Majjcom** [comment]
知道问题了，主要原因是从任务栏启动的应用的CWD和从快捷方式不一致，两个对应的可执行文件不是同一个。快捷方式启动的是启动器，从任务栏启动的是本体，二者的存放目录不同导致CWD和设计不一致，导致出现问题。如果要通过任务栏启动，可以任务栏快捷方式的运行目录(起始位置)，右键图标，再次右键，修改起始位置：去除最后的`bin`。

此问题会在下个版本修复

**Comment by Majjcom** [comment]
关于兼容性选项可以修改程序目录中bin目录下的可执行文件

**Comment by Majjcom** [comment]
在下个版本会添加高DPI支持，届时不再需要设置兼容性选项
