### ISSUE TITLE
似乎没有看到完整源码

### ISSUE THREAD

**Issue by an-Underpriviliged-ZJUer** [Majjcom/BiliDownloader#2]
hooks中引用了Js 而且有sln文件是否使用了c++

**Comment by Majjcom** [comment]
sln是用来启动用的
hooks只是吧API文件导入而已，你自己打开文件看看

怎么跑写在SETUP.md里面

自己看去

**Comment by Majjcom** [comment]
> hooks中引用了Js 而且有sln文件是否使用了c++

hooks里面的文件是给pyinstaller打包用的

还有一部分代码是用compile_ui.py生成的

请看清楚文档，谢谢
