### ISSUE TITLE
4k显示器缩放问题，ui需要微调

### ISSUE THREAD

**Issue by Reihard** [Majjcom/BiliDownloader#20]
**描述BUG**
使用4k显示器下载，下载完成后，通知栏的“打开文件夹”菜单显示粗大，不完全，似乎是这几个字固定了字体大小，看不见

**复现步骤**
4k显示器，3840x2160，缩放150%，175%
1. 
2. 
3. 
4. 

**预期的效果请描述一下你对该程序预期的效果**
调整间距

**屏幕截图**
如果可以的话，请上传发生错误的屏幕截图
![b6e40002-838b-4c8a-8302-61b8fe1c8f50](https://github.com/user-attachments/assets/5739bf3c-dfe4-4022-ba7b-fd35b49284ba)

**你使用的系统是：**
Winbugdows 10

**其他说明**
如果还有其他情况，在这里说明。

**Comment by Majjcom** [comment]
预计在下个版本添加对高DPI设备的支持。

现在有个临时解决方案：右键快捷方式->属性->兼容性->更改高DPI设置->高DPI缩放替代，打勾即可。

不过我很快会发新的版本，到时候问题就可以直接解决了
