### ISSUE TITLE
下载有分p的视频下载完后面的会自动把前面的删了

### ISSUE THREAD

**Issue by btbt236** [Majjcom/BiliDownloader#3]

**Comment by Majjcom** [comment]
具体是什么情况？哪个视频？删除的应该只是临时文件。

**Comment by Majjcom** [comment]
请说明清楚

**Comment by btbt236** [comment]
我下载一个分p的视频，下载完了之后只有最后一p的视频，其他的在下载完后一p前一个p会自动消失（存疑，没有一直盯着看）设置都是默认的，清晰度是1080p60hz，视频链接是BV1GP4y1k7ZA，

**Comment by Majjcom** [comment]
我试了一下，没有遇到这样的问题，可能是其他原因导致的
