### ISSUE TITLE
视频时长比较长时，工具开始下载会闪退

### ISSUE THREAD

**Issue by th10010** [Majjcom/BiliDownloader#8]
工具在下载4小时以上的长视频时，会自动闪退，比如下载视频BV1Kk4y1A7FZ

**Comment by Majjcom** [comment]
问题已经在其他反馈中发现。
下个版本修复。

问题原因：下载视频大小过大导致整数溢出
缓解措施：降低下载分辨率

**Comment by th10010** [comment]
感谢
