### ISSUE TITLE
解析正常，但是下载会报错

### ISSUE THREAD

**Issue by th10010** [Majjcom/BiliDownloader#9]
如图：
![1](https://github.com/Majjcom/BiliDownloader/assets/55772277/f0d4a44f-60ca-40ac-9d6c-beba74089cf0)
解析视频都一切正常，但是卡在了下载环境，提示获取链接失败

**Comment by Majjcom** [comment]
视频链接发一下，我好复现问题

**Comment by Majjcom** [comment]
我是可以下载的，登录和未登录都可以

如果你有登录过的话，可能是登录过期了，或者说是改过密码。

如果是这样可以试试重新登录

**Comment by Majjcom** [comment]
如果还有问题的话我再跟进

**Comment by th10010** [comment]
感谢解答，确实是登录状态失效了

**Comment by Majjcom** [comment]
刚好提醒我做登录验证了，下个版本安排上
